[general]
name = "ggml"
universal = false

[torch]
src = [
  "torch-ext/torch_binding.cpp",
  "torch-ext/torch_binding.h"
]

[kernel.ggml]
backend = "cuda"
depends = [ "torch" ]
src = [
  "ggml/cuda_compat.h",
  "ggml/dequantize.cuh",
  "ggml/dispatch_utils.h",
  "ggml/ggml_kernel.cu",
  "ggml/ggml-common.h",
  "ggml/mmq.cu",
  "ggml/mmq.cuh",
  "ggml/mmvq.cuh",
  "ggml/vecdotq.cuh",
]